import{a as l}from"./assets/vendor-2s9xPmg-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function i(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(t){if(t.ep)return;t.ep=!0;const n=i(t);fetch(t.href,n)}})();l.defaults.baseURL="https://energyflow.b.goit.study/api/";const q=async()=>{const{data:s}=await l.get("quote");return s},w=async(s="Muscles",e=1)=>{const i=window.innerWidth;let r=null;i<=767?r=8:r=12;const{data:t}=await l.get(`filters?filter=${s}&page=${e}&limit=${r}`);return t},$=async(s,e,i=1)=>{const r=window.innerWidth;let t=null;r<=1439?t=8:t=9;const{data:n}=await l.get(`exercises?${s}=${e}&page=${i}&limit=${t}`);return n},a={quoteBlock:document.getElementById("quote"),exerciseList:document.querySelector(".exercise-list"),pagination:document.querySelector(".pagination"),filterList:document.querySelector(".filter-list"),categoryContainer:document.querySelector(".category-container")},E=async()=>{let s=localStorage.getItem("DailyQuote"),e=s?JSON.parse(s):null;if(!e||Date.now()-e.date>864e5){const{author:r,quote:t}=await q();e={author:r,quote:t,date:Date.now()},localStorage.setItem("DailyQuote",JSON.stringify(e)),a.quoteBlock.children[1].textContent=e.quote,a.quoteBlock.children[2].textContent=e.author}a.quoteBlock.children[1].textContent=e.quote,a.quoteBlock.children[2].textContent=e.author};let c,f;const p=[...a.filterList.querySelectorAll("button[data-filter]")],g=async(s,e)=>{const{results:i,totalPages:r,page:t}=await w(s,e),n=i.map(({imgUrl:o,name:u,filter:d})=>`
          <li class="exercise-item" style="--img: url(${o})">
            <h3 class="exercise-subtitle">${u}</h3>
            <p class="exercise-name">${d}</p>
          </li>
          `).join("");a.exerciseList.innerHTML=n,a.categoryContainer.innerHTML="",S(r),y(t)},S=s=>{let e="";for(let i=1;i<=s;i++)e+=`<li class="pages_list-item">
                <button type="button" class="pages_list-btn">${i}</button>
              </li>`;a.pagination.innerHTML=e},m=async(s,e,i)=>{const{results:r,totalPages:t,page:n}=await $(s,e,i),o=r.map(({target:u,rating:d,burnedCalories:x,bodyPart:h,time:L,name:b})=>`
            <li class="exercise-info">
              <button class="startBtn" type="button">Start -></button>
              <p class="info-label">Workout</p>
              <span class="info-ranking">${String(d.toFixed(1)).padEnd(2,0)}</span>
              <h2 class="info-title">${b}</h2>
                  <ul class="info-list">
                    <li class="info-item">Burned calories: <span>${x} / ${L} min</span></li>
                    <li class="info-item">Body part: <span>${h}</span></li>
                    <li class="info-item">Target: <span>${u}</span></li>
                  </ul>
            </li>
    `).join("");a.categoryContainer.innerHTML=`<span class="exercise-category">${e}</span>`,a.exerciseList.innerHTML=o,y(n)},y=s=>{[...document.querySelectorAll(".pages_list-btn")].forEach(i=>{const r=parseFloat(i.textContent),t=parseFloat(s);r===t?(i.classList.add("active"),i.disabled=!0):(i.classList.remove("active"),i.disabled=!1)})};E();g();a.pagination.addEventListener("click",s=>{if(s.target.classList.contains("pages_list-btn")){const e=parseFloat(s.target.textContent);document.querySelector(".exercise-info")?m(f,c,e):g(c,e)}});a.filterList.addEventListener("click",s=>{const e=s.target.dataset.filter;c=s.target.textContent.trim(),e&&(p.forEach(i=>{i.classList.remove("active"),i.disabled=!1}),s.target.classList.add("active"),s.target.disabled=!0,g(c))});a.exerciseList.addEventListener("click",s=>{const e=s.target.closest(".exercise-item");e&&(c=e.children[0].textContent,f=e.children[1].textContent,p.forEach(i=>{i.disabled=!1}),m(f,c))});
//# sourceMappingURL=index.js.map
