import{a as l}from"./assets/vendor-2s9xPmg-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const i of document.querySelectorAll('link[rel="modulepreload"]'))n(i);new MutationObserver(i=>{for(const a of i)if(a.type==="childList")for(const o of a.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function t(i){const a={};return i.integrity&&(a.integrity=i.integrity),i.referrerPolicy&&(a.referrerPolicy=i.referrerPolicy),i.crossOrigin==="use-credentials"?a.credentials="include":i.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(i){if(i.ep)return;i.ep=!0;const a=t(i);fetch(i.href,a)}})();l.defaults.baseURL="https://energyflow.b.goit.study/api/";const b=async()=>{const{data:e}=await l.get("quote");return e},q=async(e="Muscles",s=1)=>{const t=window.innerWidth;let n=null;t<=767?n=8:n=12;const{data:i}=await l.get(`filters?filter=${e}&page=${s}&limit=${n}`);return i},w=async(e,s,t=1)=>{const n=window.innerWidth;let i=null;n<=1439?i=8:i=9;const{data:a}=await l.get(`exercises?${e}=${s}&page=${t}&limit=${i}`);return a},r={quoteBlock:document.getElementById("quote"),exerciseList:document.querySelector(".exercise-list"),pagination:document.querySelector(".pagination"),filterList:document.querySelector(".filter-list"),exerciseCategory:document.querySelector(".exercise-category")},S=async()=>{if(localStorage.getItem("DailyQuote")){const e=new Date,s=`Day: ${e.getDay()} / Month: ${e.getMonth()} / Year: ${e.getFullYear()}`,{quote:t,author:n,date:i}=JSON.parse(localStorage.getItem("DailyQuote"));i===s&&(r.quoteBlock.children[1].textContent=t,r.quoteBlock.children[2].textContent=n)}else{const{author:e,quote:s}=await b(),t=new Date,n={quote:s,author:e,date:`Day: ${t.getDay()} / Month: ${t.getMonth()} / Year: ${t.getFullYear()}`};localStorage.setItem("DailyQuote",JSON.stringify(n)),r.quoteBlock.children[1].textContent=s,r.quoteBlock.children[2].textContent=e}};let c,g;const p=[...r.filterList.querySelectorAll("button[data-filter]")],f=async(e,s)=>{const{results:t,totalPages:n,page:i}=await q(e,s),a=t.map(({imgUrl:o,name:u,filter:d})=>`
          <li class="exercise-item" style="--img: url(${o})">
            <h3 class="exercise-subtitle">${u}</h3>
            <p class="exercise-name">${d}</p>
          </li>
          `).join("");r.exerciseList.innerHTML=a,B(n),y(i)},B=e=>{let s="";for(let t=1;t<=e;t++)s+=`<li class="pages_list-item">
                <button type="button" class="pages_list-btn">${t}</button>
              </li>`;r.pagination.innerHTML=s},m=async(e,s,t)=>{const{results:n,totalPages:i,page:a}=await w(e,s,t),o=n.map(({target:u,rating:d,burnedCalories:x,bodyPart:h,time:L,name:$})=>`
            <li class="exercise-info">
              <button class="startBtn" type="button">Start -></button>
              <p class="info-label">Workout</p>
              <span class="info-ranking">${String(d.toFixed(1)).padEnd(2,0)}</span>
              <h2 class="info-title">${$}</h2>
                  <ul class="info-list">
                    <li class="info-item">Burned calories: <span>${x} / ${L} min</span></li>
                    <li class="info-item">Body part: <span>${h}</span></li>
                    <li class="info-item">Target: <span>${u}</span></li>
                  </ul>
            </li>
    `).join("");r.exerciseList.innerHTML=o,y(a)},y=e=>{[...document.querySelectorAll(".pages_list-btn")].forEach(t=>{const n=parseFloat(t.textContent),i=parseFloat(e);n===i?(t.classList.add("active"),t.disabled=!0):(t.classList.remove("active"),t.disabled=!1)})};S();f();r.pagination.addEventListener("click",e=>{if(e.target.classList.contains("pages_list-btn")){const s=parseFloat(e.target.textContent);document.querySelector(".exercise-info")?m(g,c,s):f(c,s)}});r.filterList.addEventListener("click",e=>{const s=e.target.dataset.filter;c=e.target.textContent.trim(),s&&(p.forEach(t=>{t.classList.remove("active"),t.disabled=!1}),e.target.classList.add("active"),e.target.disabled=!0,f(c))});r.exerciseList.addEventListener("click",e=>{const s=e.target.closest(".exercise-item");s&&(c=s.children[0].textContent,g=s.children[1].textContent,p.forEach(t=>{t.disabled=!1}),m(g,c))});
//# sourceMappingURL=index.js.map
